server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url:  kamothi-db.cznhzw13ae95.ap-northeast-2.rds.amazonaws.com
    username: kamothi-db
    password: znrnfl1
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
